//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int ID { get; set; }
        public decimal TotalAPagar { get; set; }
        public int Efectivo { get; set; }
        public int Cambio { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ClienteID { get; set; }
        public int TipoPagoID { get; set; }
        public int EmpleadoID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
