//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioIngrediente
    {
        public int ID { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public System.DateTime caducidad { get; set; }
        public int InventarioID { get; set; }
        public int IngredienteID { get; set; }
        public int stock { get; set; }
        public bool estado { get; set; }
    
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
