//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioAlmacen
    {
        public int ID { get; set; }
        public int InventarioID { get; set; }
        public int AlmacenID { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
