//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservacion()
        {
            this.ReservaMesa = new HashSet<ReservaMesa>();
        }
    
        public int ID { get; set; }
        public int SucursalID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime FechaDeSolicitud { get; set; }
        public System.DateTime FechaDeReservacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaMesa> ReservaMesa { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
